### ISSUE TITLE
NameError: uninitialized constant StateMachine::YARD::Handlers::Machine::Integrations

### ISSUE THREAD

**Issue by bacrossland** [state-machines/state_machines-yard#6]
When running yardoc on a Rails app that uses this gem, I get the following error:

```
[error]: NameError: uninitialized constant StateMachine::YARD::Handlers::Machine::Integrations
[error]: Stack trace:
	/Users/bcrossland/.rvm/gems/jruby-1.7.25@fp2/gems/state_machines-yard-0.0.1/lib/state_machines/yard/handlers/machine.rb:120:in `integration'
	/Users/bcrossland/.rvm/gems/jruby-1.7.25@fp2/gems/state_machines-yard-0.0.1/lib/state_machines/yard/handlers/machine.rb:158:in `define_macro_methods'
	/Users/bcrossland/.rvm/gems/jruby-1.7.25@fp2/gems/state_machines-yard-0.0.1/lib/state_machines/yard/handlers/machine.rb:41:in `process'
	/Users/bcrossland/.rvm/gems/jruby-1.7.25@fp2/gems/yard-0.9.8/lib/yard/handlers/processor.rb:114:in `process'
	/Users/bcrossland/.rvm/gems/jruby-1.7.25@fp2/gems/yard-0.9.8/lib/yard/handlers/processor.rb:112:in `each'
	/Users/bcrossland/.rvm/gems/jruby-1.7.25@fp2/gems/yard-0.9.8/lib/yard/handlers/processor.rb:112:in `process'
```

Looking at #1 I can see that fixes were merged in, however, the gem version was never updated and never released.

Installing the gem using the following in a Gemfile fetches the outdated version with the bad namespacing.

```
gem 'state_machines-yard'
```

Specifying the GitHub repo in my Gemfile got around the issue but it's not ideal.

```
gem 'state_machines-yard', :github => 'state-machines/state_machines-yard'
```

The gem version needs to be updated and released to rubygems.org.

**Comment by seuros** [comment]
How did i miss this ..
